In [1]:
import pandas as pd

In [10]:
df_complaints=pd.read_csv("data/complaints20_25_original.csv")
print(df_complaints.isna().sum())
df_complaints.head()

unique_key          0
created_date        0
agency_name         0
complaint_type      0
incident_zip        0
council_district    0
borough             0
dtype: int64

,unique_key,created_date,agency_name,complaint_type,incident_zip,council_district,borough
0,67350845,2025-12-31 23:57:56,Department of Housing Preservation and Develop...,HEAT/HOT WATER,11229,46,BROOKLYN
1,67347338,2025-12-31 23:54:46,Department of Housing Preservation and Develop...,HEAT/HOT WATER,11239,42,BROOKLYN
2,67350847,2025-12-31 23:54:42,Department of Housing Preservation and Develop...,HEAT/HOT WATER,10040,10,MANHATTAN
3,67346000,2025-12-31 23:54:41,Department of Housing Preservation and Develop...,HEAT/HOT WATER,10463,10,MANHATTAN
4,67349568,2025-12-31 23:54:14,Department of Housing Preservation and Develop...,HEAT/HOT WATER,10454,8,BRONX

In [11]:
df_complaints = df_complaints.drop(columns=["agency_name"])
df_complaints.head()

,unique_key,created_date,complaint_type,incident_zip,council_district,borough
0,67350845,2025-12-31 23:57:56,HEAT/HOT WATER,11229,46,BROOKLYN
1,67347338,2025-12-31 23:54:46,HEAT/HOT WATER,11239,42,BROOKLYN
2,67350847,2025-12-31 23:54:42,HEAT/HOT WATER,10040,10,MANHATTAN
3,67346000,2025-12-31 23:54:41,HEAT/HOT WATER,10463,10,MANHATTAN
4,67349568,2025-12-31 23:54:14,HEAT/HOT WATER,10454,8,BRONX

In [6]:
df_complaints["incident_zip"].value_counts()

incident_zip
11226    11341
10452    10295
10458     9930
10467     9271
10468     9099
         ...
11697        2
10803        2
10177        1
10020        1
10271        1
Name: count, Length: 188, dtype: int64

In [12]:
df_complaints["complaint_type"].value_counts()

complaint_type
HEAT/HOT WATER          172346
UNSANITARY CONDITION     86834
PLUMBING                 47505
WATER LEAK               27934
ELECTRIC                 21052
Name: count, dtype: int64